name: Daily SHPGX Data Update

on:
  schedule:
    - cron: '0 1 * * *'  # 9am SGT
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Allow push access for GITHUB_TOKEN
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run update script
        run: python update_shpgx_data.py

      - name: Commit & push CSV if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add shpgx_price_index.csv
          git diff --cached --quiet || git commit -m "Daily update"
          git push
